#!/bin/bash

planners=("fast-downward" "parser" "arvand" "dae_yahsp" "lama-2008" "lamar" "lpg" "madagascar" 
"probe" "randward" "sgplan" "yahsp2-mt" "features" "preprocess-old")




cd "$(dirname "$0")"
ROOT=$PWD


for item in ${planners[*]}
do
	planner_path="$ROOT"/src/"$item"
	echo -e "\n**************************"
	echo "*** Compiling" $item "***" 
	echo -e "**************************\n"
	cd $planner_path
	./build

	if [ $? -ne 0 ]; then
		echo -e "\nCompilation error when compiling:" $item 
		exit 1
	fi

done

echo -e "\nPlanner ready to the International Planning Competition 2014"
