#!/bin/bash
BASEDIR="$(dirname "$0")"

# Paths to planner components
TRANSLATE="$BASEDIR/translate/translate.py" ##change
PREPROCESS="$BASEDIR/preprocess/preprocess" ##change
SEARCH="$BASEDIR/search/release-search"


if [ $# -ne 3 ]; then
	echo "Usage: "$0" <domain_file> <problem_file> <result_file>"
	exit 1
else

    echo "1. Running translator"
    python2.7 "$TRANSLATE" "$1" "$2"
    echo "2. Running preprocessor"
    "$PREPROCESS" < output-old.sas
    echo "3. Running search"
    "$SEARCH" "fFiR2011" "$3" < output-old

fi
