#!/bin/sh

source /opt/centos/devtoolset-1.1/x86_64/enable

cd "$(dirname "$0")"
ROOT=$PWD

cd $ROOT/preprocess && \
(make || exit 1)
cd $ROOT/search && \
(make release || exit 1)


if [ $? -eq 0 ]; then
	cd $ROOT/

else 
	exit 1
fi
