#!/bin/bash

cd "$(dirname "$0")"
ROOT=$PWD

cd $ROOT/data/bin/LPG_quality 
make clean
./configure
cp lpg $ROOT/data/bin/lpg_itera


cd $ROOT/data/bin/LPG_pbp_dir
make clean
./configure
cp lpg $ROOT/data/bin/lpg_pbp


cd $ROOT/data/bin/LPG_conf_learn/
./configure
cp lpg $ROOT/data/bin/lpg_par


cd $ROOT/data/bin/LPG_conf_test/
./configure
cp lpg $ROOT/data/bin/lpg_par_test


cd $ROOT/data/bin/
g++ lpg_config.c -o abstraction_learn
g++ lpg_config_test.c -o abstraction_pbp


